namespace Refulgence.Dxbc;

public enum PrimitiveTopology : uint
{
    Undefined = 0,
    PointList = 1,
    LineList = 2,
    LineStrip = 3,
    TriangleList = 4,
    TriangleStrip = 5,
    TriangleFan,
    LineListAdj = 10,
    LineStripAdj = 11,
    TriangleListAdj = 12,
    TriangleStripAdj = 13,
    PatchList1ControlPoint = 33,
    PatchList2ControlPoint = 34,
    PatchList3ControlPoint = 35,
    PatchList4ControlPoint = 36,
    PatchList5ControlPoint = 37,
    PatchList6ControlPoint = 38,
    PatchList7ControlPoint = 39,
    PatchList8ControlPoint = 40,
    PatchList9ControlPoint = 41,
    PatchList10ControlPoint = 42,
    PatchList11ControlPoint = 43,
    PatchList12ControlPoint = 44,
    PatchList13ControlPoint = 45,
    PatchList14ControlPoint = 46,
    PatchList15ControlPoint = 47,
    PatchList16ControlPoint = 48,
    PatchList17ControlPoint = 49,
    PatchList18ControlPoint = 50,
    PatchList19ControlPoint = 51,
    PatchList20ControlPoint = 52,
    PatchList21ControlPoint = 53,
    PatchList22ControlPoint = 54,
    PatchList23ControlPoint = 55,
    PatchList24ControlPoint = 56,
    PatchList25ControlPoint = 57,
    PatchList26ControlPoint = 58,
    PatchList27ControlPoint = 59,
    PatchList28ControlPoint = 60,
    PatchList29ControlPoint = 61,
    PatchList30ControlPoint = 62,
    PatchList31ControlPoint = 63,
    PatchList32ControlPoint = 64,
}
