namespace Refulgence.Dxbc.ResourceDefinition;

public enum ShaderVariableType : ushort
{
    Void                    = 0,
    Bool                    = 1,
    Int                     = 2,
    Float                   = 3,
    String                  = 4,
    Texture                 = 5,
    Texture1D               = 6,
    Texture2D               = 7,
    Texture3D               = 8,
    TextureCube             = 9,
    Sampler                 = 10,
    Sampler1D               = 11,
    Sampler2D               = 12,
    Sampler3D               = 13,
    SamplerCube             = 14,
    PixelShader             = 15,
    VertexShader            = 16,
    PixelFragment           = 17,
    VertexFragment          = 18,
    UInt                    = 19,
    UInt8                   = 20,
    GeometryShader          = 21,
    Rasterizer              = 22,
    DepthStencil            = 23,
    Blend                   = 24,
    Buffer                  = 25,
    CBuffer                 = 26,
    TBuffer                 = 27,
    Texture1DArray          = 28,
    Texture2DArray          = 29,
    RenderTargetView        = 30,
    DepthStencilView        = 31,
    Texture2DMS             = 32,
    Texture2DMSArray        = 33,
    TextureCubeArray        = 34,
    HullShader              = 35,
    DomainShader            = 36,
    InterfacePointer        = 37,
    ComputeShader           = 38,
    Double                  = 39,
    RWTexture1D             = 40,
    RWTexture1DArray        = 41,
    RWTexture2D             = 42,
    RWTexture2DArray        = 43,
    RWTexture3D             = 44,
    RWBuffer                = 45,
    ByteAddressBuffer       = 46,
    RWByteAddressBuffer     = 47,
    StructuredBuffer        = 48,
    RWStructuredBuffer      = 49,
    AppendStructuredBuffer  = 50,
    ConsumeStructuredBuffer = 51,
    Min8Float               = 52,
    Min10Float              = 53,
    Min16Float              = 54,
    Min12Int                = 55,
    Min16Int                = 56,
    Min16UInt               = 57,
    Int16,
    UInt16,
    Float16,
    Int64,
    UInt64,
}
